apiVersion: apps/v1
kind: Deployment
metadata:
  name: betops-worker
  namespace: betops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betops-worker
  template:
    metadata:
      labels:
        app: betops-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/ilaycohen12/betops-worker:latest
          env:
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: betops-secrets
                  key: SQS_QUEUE_URL
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: betops-secrets
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: betops-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: betops-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: betops-secrets
                  key: DB_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: betops-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: betops-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
